Logistic regression

Use sklearn.datasets iris flower dataset to train your model using logistic regression. You need to figure out accuracy of your model and use that to predict different samples in your test dataset. In iris dataset there are 150 samples containing following features,

Sepal Length
Sepal Width
Petal Length
Petal Width
Using above 4 features you will classify a flower in one of the three categories,

Setosa
Versicolour
Virginica

In [1]:
#importing our libraries
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import warnings 
warnings.filterwarnings("ignore")

In [2]:
#loading one of the sklearn datasets called iris
iris_flower = load_iris()


In [3]:
#the directory of the iris datasets
dir(iris_flower)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
#displaying the datasets showing the independent variables
iris_flower.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
#displaying the dependent variable
iris_flower.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
#Displaying the independent variable names
iris_flower.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
#displaying the datasets showing the dependent variables
iris_flower.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# Creating a dataframe for the independent variable
irisdata = pd.DataFrame(iris_flower.data, columns = iris_flower.feature_names)
irisdata.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
#Joining the dependent variables 'target' to our dataframe
irisdata['target'] = iris_flower.target
irisdata.sample(5)


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
103                6.3               2.9                5.6               1.8   
89                 5.5               2.5                4.0               1.3   
6                  4.6               3.4                1.4               0.3   
69                 5.6               2.5                3.9               1.1   
145                6.7               3.0                5.2               2.3   

     target  
103       2  
89        1  
6         0  
69        1  
145       2

In [10]:
#Extracting our independent variable (y) and displaying the remaining dependent variables (x)
x = irisdata.drop (columns =['target'])
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
#Extracting the dependent variable and displaying the dependent variable (y)
y = irisdata.drop(columns=['sepal length (cm)','sepal width (cm)', 'petal length (cm)', 'petal width (cm)'])
y

target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [12]:
#Calling the object model 
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()


In [13]:
#Splitting our test and train data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2 )

In [14]:
#checking the length of the train data to show that it is 120 rows
len(x_train)

120

In [15]:
# showing the train data as we have splitted it to be 80% of 150 i.e. 120 rows
x_train 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
114                5.8               2.8                5.1               2.4
19                 5.1               3.8                1.5               0.3
3                  4.6               3.1                1.5               0.2
20                 5.4               3.4                1.7               0.2
62                 6.0               2.2                4.0               1.0
..                 ...               ...                ...               ...
37                 4.9               3.6                1.4               0.1
10                 5.4               3.7                1.5               0.2
74                 6.4               2.9                4.3               1.3
72                 6.3               2.5                4.9               1.5
138                6.0               3.0                4.8               1.8

[120 rows x 4 columns]

In [16]:
#checking the length to be sure that it is 30 rows of data
len(x_test)

30

In [17]:
# showing the test data as we have splitted it to be 20% of 150 i.e. 30 rows
x_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
115                6.4               3.2                5.3               2.3
56                 6.3               3.3                4.7               1.6
48                 5.3               3.7                1.5               0.2
88                 5.6               3.0                4.1               1.3
67                 5.8               2.7                4.1               1.0
68                 6.2               2.2                4.5               1.5
111                6.4               2.7                5.3               1.9
61                 5.9               3.0                4.2               1.5
102                7.1               3.0                5.9               2.1
51                 6.4               3.2                4.5               1.5
49                 5.0               3.3                1.4               0.2
53                 5.5               2.3                4.0               1.3
11                 4.8               3.4                1.6               0.2
18                 5.7               3.8                1.7               0.3
66                 5.6               3.0                4.5               1.5
82                 5.8               2.7                3.9               1.2
79                 5.7               2.6                3.5               1.0
144                6.7               3.3                5.7               2.5
28                 5.2               3.4                1.4               0.2
40                 5.0               3.5                1.3               0.3
69                 5.6               2.5                3.9               1.1
98                 5.1               2.5                3.0               1.1
104                6.5               3.0                5.8               2.2
145                6.7               3.0                5.2               2.3
96                 5.7               2.9                4.2               1.3
131                7.9               3.8                6.4               2.0
130                7.4               2.8                6.1               1.9
75                 6.6               3.0                4.4               1.4
77                 6.7               3.0                5.0               1.7
7                  5.0               3.4                1.5               0.2

In [18]:
#Fitting our model for the training 
fit_model = model.fit(x, y)
fit_model

LogisticRegression()

In [19]:
#Predicting the model with the array
prediction = fit_model.predict(x_test)
prediction

array([2, 1, 0, 1, 1, 1, 2, 1, 2, 1, 0, 1, 0, 0, 1, 1, 1, 2, 0, 0, 1, 1,
       2, 2, 1, 2, 2, 1, 2, 0])

In [20]:
print('Prediction is: {} ' .format(prediction))

Prediction is: [2 1 0 1 1 1 2 1 2 1 0 1 0 0 1 1 1 2 0 0 1 1 2 2 1 2 2 1 2 0] 


In [21]:
#Checking the accuracy of the model
fit_model.score(x, y)

0.9733333333333334